<?php

namespace PyaeSoneAung\ToRawSql\Services;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Query\Builder as QueryBuilder;
use Illuminate\Support\Str;
use PyaeSoneAung\ToRawSql\Exceptions\ToRawSqlException;

class BuilderToRawSqlService
{
    public function __construct(
        public EloquentBuilder|QueryBuilder $builder
    ) {
        $placeholderCount = Str::substrCount($this->builder->toSql(), '?');
        $bindingCount = count($this->builder->getBindings());
        if ($placeholderCount !== $bindingCount) {
            throw new ToRawSqlException('The `toRawSql()` method is unable to generate raw SQL for your query at this time. This error may occur if your query contains PostgreSQL jsonb operators. Please use the `toSql()` method instead to retrieve the SQL generated by the query builder.');
        }
    }

    public function toRawSql(): string
    {
        $bindings = $this->builder->getBindings();
        foreach ($bindings as $key => $value) {
            if ($value instanceof DateTimeInterface) {
                $bindings[$key] = "'{$value->format('Y-m-d H:i:s')}'";
            } elseif (is_string($value)) {
                $bindings[$key] = "'{$value}'";
            } elseif (is_bool($value)) {
                $bindings[$key] = $value ? 'true' : 'false';
            }
        }

        return Str::replaceArray('?', $bindings, $this->builder->toSql());
    }
}
